import { useState } from 'react'
import { NavLink, useNavigate } from 'react-router-dom'
import { Activity, Bell, BrainCircuit, CalendarCheck, ChevronDown, ClipboardList, HeartPulse, LayoutDashboard, Menu, MessageSquare, MonitorSmartphone, Search, Settings, ShieldCheck, Stethoscope, Users, Wifi, X } from 'lucide-react'
import { useVirtualWardStore } from '../stores/useVirtualWardStore'
import type { Role } from '../types/domain'
import { Badge, Connectivity, CustomSelect } from './UI'

const sections=[
  ['OVERVIEW',[['Virtual Ward','/',LayoutDashboard]]],['PATIENTS',[['Active Patients','/patients',Users],['Patient Monitoring','/monitoring',HeartPulse],['Enrolments','/enrolments',ClipboardList]]],['MONITORING',[['Live Observations','/live-observations',Activity],['Alerts','/alerts',Bell],['Missing Readings','/missing-readings',CalendarCheck]]],['CARE MANAGEMENT',[['Care Plans','/care-plans',ClipboardList],['Medication Adherence','/medications',ShieldCheck],['Tasks','/tasks',CalendarCheck]]],['CLINICAL',[['Nurse Reviews','/nurse-reviews',Stethoscope],['Doctor Escalations','/doctor-escalations',HeartPulse],['Virtual Consultations','/consultations',MonitorSmartphone],['Communications','/communications',MessageSquare]]],['INTELLIGENCE',[['AI Insights','/ai-insights',BrainCircuit],['Risk Overview','/risk-overview',ShieldCheck],['Population Trends','/population-trends',Activity]]],['SYSTEM',[['Devices','/devices',Wifi],['Integrations','/integrations',MonitorSmartphone],['Audit Trail','/audit',ClipboardList],['Settings','/settings',Settings]]]
] as const
const roles:Role[]=['Virtual Ward Nurse','Consultant Physician','Remote Care Coordinator','Pharmacist','Operations Manager','Administrator','Patient / Caregiver']
export default function Layout({children}:{children:React.ReactNode}){
 const [mobile,setMobile]=useState(false),[search,setSearch]=useState(''),[profile,setProfile]=useState(false),[facility,setFacility]=useState('General Virtual Ward');const navigate=useNavigate();const {patients,alerts,devices,role,setRole}=useVirtualWardStore();const openAlerts=alerts.filter(a=>!['Resolved','Dismissed'].includes(a.status)).length;const connected=devices.filter(d=>d.status==='Connected').length
 const doSearch=()=>{const q=search.toLowerCase().trim();const p=patients.find(p=>[p.name,p.id,p.episodeId,p.pathway,p.nurse,p.consultant].some(v=>v.toLowerCase().includes(q)));const d=devices.find(d=>[d.id,d.type,d.serialDemoId].some(v=>v.toLowerCase().includes(q)));if(p)navigate(`/patients/${p.id}`);else if(d)navigate('/devices');else if(q)navigate(`/patients?search=${encodeURIComponent(q)}`);setSearch('')}
 return <div className="app-shell"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark"><Activity/></div><div><b>VIRTUALWARD</b><span>AI</span><small>REMOTE CARE</small></div><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><nav>{sections.map(([label,links])=><div className="nav-section" key={label}><small>{label}</small>{links.map(([name,path,Icon])=><NavLink key={path} to={path} end={path==='/'} onClick={()=>setMobile(false)}><Icon/>{name}</NavLink>)}</div>)}</nav><NavLink className="patient-demo-link" to="/patient-demo"><MessageSquare/>Patient demo mode</NavLink></aside>
 <div className="app-main"><header className="topbar"><button className="menu-btn" onClick={()=>setMobile(true)}><Menu/></button><div className="facility"><span><b>Northbridge Virtual Care Service</b><small>Facility / Virtual Ward</small></span><CustomSelect ariaLabel="Facility and Virtual Ward" value={facility} onChange={setFacility} options={['General Virtual Ward','Respiratory Virtual Ward','Post-acute Virtual Ward'].map(value=>({value,label:value}))}/></div><form className="global-search" onSubmit={e=>{e.preventDefault();doSearch()}}><Search/><input aria-label="Global search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search patient, episode, device..."/></form><Connectivity online={connected>0}/><button className="notification" aria-label={`${openAlerts} open notifications`} onClick={()=>navigate('/notifications')}><Bell/><Badge tone="danger">{openAlerts}</Badge></button><div className="profile-wrap"><button className="profile" onClick={()=>setProfile(!profile)}><span className="avatar">RM</span><span><b>Rebecca Morgan</b><small>{role}</small></span><ChevronDown/></button>{profile&&<div className="role-menu"><b>Simulate role</b>{roles.map(r=><button className={role===r?'active':''} key={r} onClick={()=>{setRole(r);setProfile(false)}}>{r}</button>)}</div>}</div><Badge tone="info">Demo environment</Badge></header><main>{children}</main></div></div>
}
